"""add role

Revision ID: 0ceff09fd79b
Revises: e3c4d72bcd2f
Create Date: 2022-12-07 08:51:59.809621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ceff09fd79b'
down_revision = 'e3c4d72bcd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), server_default='simple', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
